import Head from 'next/head'
import {fetchPostSlugs} from 'utils/fetchPostSlugs'
import PageLayout from 'components/layouts/page-layout'
import {PostCard} from 'components/blog/'
import {Post} from 'types/blog/'

type BlogPageProps = {
  posts: Post[]
}

const Blog: React.FC<BlogPageProps> = ({posts}) => {
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h2>Posts:</h2>
        <ul className="mt-8 space-y-6">
          {posts.map((post) => {
            return <PostCard post={post} key={post.slug} />
          })}
        </ul>
      </div>
    </PageLayout>
  )
}

export default Blog

export async function getStaticProps() {
  const slugs = await fetchPostSlugs()
  const posts = slugs.map((slug) => {
    const meta = require(`./posts/${slug}/index.mdx`).meta
    return {
      slug,
      meta,
    }
  })
  return {
    props: {
      posts,
    },
  }
}
