import type {NextPage} from 'next'
import Head from 'next/head'
import {posts} from 'utils/get-all-posts'
import PageLayout from 'components/layouts/page-layout'

const Blog: NextPage = () => {
  console.log('Posts:', posts)
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">Posts:</div>
    </PageLayout>
  )
}

export default Blog
