import Head from 'next/head'
import {getAllPosts} from 'utils/posts'
import PageLayout from 'components/layouts/page-layout'
import {PostCard} from 'components/blog/'
import {Post} from 'types/blog/'

type BlogPageProps = {
  // posts: Post[]
  posts: any
}

const Blog: React.FC<BlogPageProps> = ({posts}) => {
  console.log('posts:', posts)
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h2>Posts:</h2>
        <ul className="mt-8 space-y-6">
          {posts.map((post: any) => {
            return <PostCard post={post} key={post.slug} />
          })}
        </ul>
      </div>
    </PageLayout>
  )
}

export default Blog

export function getStaticProps() {
  const posts = getAllPosts(['slug', 'source', 'frontMatter'])
  return {
    props: {
      posts,
    },
  }
}
