import Head from 'next/head'
import Link from 'next/link'
import {fetchPostSlugs} from 'utils/fetchPostSlugs'
import PageLayout from 'components/layouts/page-layout'

const Blog: React.FC<any> = ({posts}) => {
  return (
    <PageLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h2>Posts:</h2>
        <ul className="mt-8 space-y-6">
          {posts.map((post: any, index: number) => {
            return (
              <div
                key={index}
                className="flex flex-col p-4 space-y-4 bg-blue-dark"
              >
                <h3>
                  <Link href={`/blog/${post.slug}`}>
                    <a className="text-white">{post.meta.title}</a>
                  </Link>
                </h3>
                <p>{post.meta.excerpt}</p>
                <p>{post.meta.date}</p>
                <div className="flex space-x-2">
                  <div>Tags:</div>
                  <div className="flex">{post.meta.tags.join(', ')}</div>
                </div>
              </div>
            )
          })}
        </ul>
      </div>
    </PageLayout>
  )
}

export default Blog

export async function getStaticProps() {
  const slugs = await fetchPostSlugs()
  const posts = slugs.map((slug) => {
    const meta = require(`./blog/${slug}/index.mdx`).meta
    return {
      slug,
      meta,
    }
  })
  return {
    props: {
      posts,
    },
  }
}
